#!/bin/bash

python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test1.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test2.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test3.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test4.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test5.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test6.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test7.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test8.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test9.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test10.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test11.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test12.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test13.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test14.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test15.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test16.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test17.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test18.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test19.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test20.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test21.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test22.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test23.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test24.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test25.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test26.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test27.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test28.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test29.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test30.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test31.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test32.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test33.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test34.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test35.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test36.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test37.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test38.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test39.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test40.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test41.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test42.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test43.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test44.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test45.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test46.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test47.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test48.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test49.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test50.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test51.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test52.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test53.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test54.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test55.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test56.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test57.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test58.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test59.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test60.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test61.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test62.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test63.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test64.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test65.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test66.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test67.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test68.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test69.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test70.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test71.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test72.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test73.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test74.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test75.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test76.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test77.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test78.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test79.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test80.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test81.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test82.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test83.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test84.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test85.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test86.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test87.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test88.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test89.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test90.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test91.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test92.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test93.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test94.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test95.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test96.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test97.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test98.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test99.txt
python3 BlackJack.py strategy/BasicStrategyNoSr.csv 1 1 > ./tests/test100.txt